// patient action types
export const ADD_PATIENT = "ADD_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const ADD_PATIENT_APPOINTMENT = "ADD_PATIENT_APPOINTMENT";
export const DELETE_PATIENT_APPOINTMENT = "DELETE_PATIENT_APPOINTMENT";

// doctor action types
export const ADD_DOCTOR = "ADD_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const ADD_DOCTOR_APPOINTMENT = "ADD_DOCTOR_APPOINTMENT";
export const DELETE_DOCTOR_APPOINTMENT = "DELETE_DOCTOR_APPOINTMENT";