// patient action types
export const ADD_PATIENT = "ADD_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const ADD_PATIENT_APPOINTMENT = "ADD_PATIENT_APPOINTMENT";
export const DELETE_PATIENT_APPOINTMENT = "DELETE_PATIENT_APPOINTMENT";

// doctor action types
export const ADD_DOCTOR = "ADD_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const ADD_DOCTOR_APPOINTMENT = "ADD_DOCTOR_APPOINTMENT";
export const DELETE_DOCTOR_APPOINTMENT = "DELETE_DOCTOR_APPOINTMENT";


//procedure action types
export const ADD_PROCEDURE = "ADD_PROCEDURE";
export const DELETE_PROCEDURE = "DELETE_PROCEDURE";
export const UPDATE_PROCEDURE = "UPDATE_PROCEDURE";
export const ADD_PROCEDURE_APPOINTMENT = "ADD_PROCEDURE_APPOINTMENT";
export const DELETE_PROCEDURE_APPOINTMENT = "DELETE_PROCEDURE_APPOINTMENT"



// appointments action types
export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";


//user action
export const SET_USER = "SET_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";


//admin action
export const ADD_ADMIN = "SET_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const UPDATE_ADMIN = "UPDATE_ADMIN";


