export const ADD_PATIENT = "ADD_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const ADD_PATIENT_APPOINTMENT = "ADD_PATIENT_APPOINTMENT";